### ISSUE TITLE
How `reviews` parameter works

### ISSUE THREAD

**Issue by saewitz** [Planet-Terp/PlanetTerp-API-Python-Wrapper#3]
Currently, the `reviews` option for courses and professors seems to work like this:

`planetterp.course(name="CMSC133", reviews="true")`

I think this would be more effective, because `reviews` is a boolean:

`planetterp.course(name="CMSC133", reviews=True)`

Thoughts?

**Comment by ethan-schaffer** [comment]
Makes sense. 👍
