### ISSUE TITLE
How `limit` parameter works

### ISSUE THREAD

**Issue by saewitz** [Planet-Terp/PlanetTerp-API-Python-Wrapper#4]
Similar to #3.

Currently, the `limit` option for courses and professors seems to work like this:

`planetterp.all_courses(limit="1001")`

I think this would be more effective, because `limit` is an integer:

`planetterp.all_courses(limit=1001)`

Thoughts?

If we make this change, we should also change `offset` to be an integer.

**Comment by ethan-schaffer** [comment]
This makes sense to me! Nice catch.
